spring.application.name=sovereign-ai-workbench

spring.config.import=optional:file:C:/Users/divsutar/OneDrive/Desktop/navproject/SIH 2026/Nexus-LLM/ai-backend/sovereign-ai-workbench/local.properties

server.port=${PORT:8090}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

spring.ai.openai.api-key=${AI_KEY}
spring.ai.openai.base-url=https://integrate.api.nvidia.com/v1
spring.ai.openai.chat.model=nvidia/nemotron-3-ultra-550b-a55b
spring.ai.openai.chat.max-tokens=10000

spring.ai.model.embedding=none

logging.level.org.springframework.ai.openai=DEBUG
logging.level.com.openai=DEBUG

spring.ai.chat.memory.repository.jdbc.initialize-schema=always

